---

- name: dependencies
  yum: name={{ item }} state=latest
  with_items:
    - git
    - gzip
    - tar
    - gcc
    - make
    - bison
    - ncurses-devel
    - zlib-devel
    - libevent-devel
    - cmake
    - openssl
    - jemalloc
- file: path={{ mariadb_root }} state=directory
- unarchive: src={{ mariadb_download_url }} dest={{ download_src }} copy=no
- group: name={{ mariadb_group }} state=present
- user: name={{ mariadb_user }} group={{ mariadb_group }} system=yes createhome=no shell=/sbin/nologin
- name: check mysql service
  stat: path=/etc/init.d/mysqld
  register: service_status
- name: stop mysql service
  service: name=mysqld state=stopped
  when: service_status.stat.exists
  register: service_stopped
- name: install mariadb
  shell: >
    cd {{ download_src }}/mariadb-{{ mariadb_version }} &&
    BUILD/autorun.sh &&
    ./configure --prefix={{ mariadb_root }}/mysql-{{ mariadb_version }}
    --enable-assembler
    --with-extra-charsets=complex
    --enable-thread-safe-client
    --with-big-tables
    --with-plugin-maria
    --with-aria-tmp-tables
    --without-plugin-innodb_plugin
    --with-mysqld-ldflags=-static
    --with-client-ldflags=-static
    --with-readline
    --with-ssl
    --with-plugins=max-no-ndb
    --with-embedded-server
    --with-libevent
    --with-mysqld-ldflags=-all-static
    --with-client-ldflags=-all-static
    --with-zlib-dir=bundled
    --enable-local-infile &&
    make &&
    make install
- file:
    src: "{{ mariadb_root }}/mysql-{{ mariadb_version }}"
    dest: "{{ mariadb_root }}/current"
    state: link
- name: mariadb PATH
  shell: >
    echo "export PATH=\$PATH:{{ mariadb_root }}/current/bin" > /etc/profile.d/mysql.sh
- file: path=/etc/profile.d/mysql.sh mode=0644 owner=root
- copy:
    remote_src: true
    src: "{{ mariadb_root }}/current/support-files/mysql.server"
    dest: /etc/init.d/mysqld
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
- name: set mysql datadir
  lineinfile:
    #ansible2.3以降はdestではなくpath
    dest: /etc/init.d/mysqld
    state: present
    regexp: "^datadir=$"
    line: "datadir={{ mariadb_datadir }}"
- template:
    src: templates/my.ini
    dest: "{{ mariadb_root }}/current/my.cnf"
- name: set my.cnf datadir
  lineinfile:
    #ansible2.3以降はdestではなくpath
    dest: "{{ mariadb_root }}/current/my.cnf"
    state: present
    regexp: "^datadir =$"
    line: "datadir = {{ mariadb_datadir }}"
- file: path="{{ mariadb_datadir }}" state=directory owner="{{ mariadb_user }}"
- name: mysql_install_db
  become: yes
  become_user: "{{ mariadb_user }}"
  command: "{{ mariadb_root }}/current/scripts/mysql_install_db --no-defaults --basedir={{ mariadb_root }}/current --datadir={{ mariadb_datadir }}"
- service: name=mysqld state=started
